name: CI

on:
  release:
    types: [published]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tofu:    { type: boolean, default: false }
      ansible: { type: boolean, default: false }
permissions:
  id-token: write
  contents: read

env:
  IMAGE_TAG: ${{ github.event.release.tag_name  }}  
jobs:
  packer-validate:                     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: packer validate -syntax-only .
        working-directory: packer

  packer-deploy:
    needs: packer-validate
    runs-on: self-hosted
    environment: prod
    env:
      PKR_VAR_IMAGE_TAG: ${{ github.event.release.tag_name  }}  
    if: github.event_name  == 'release'
    steps:
      - uses: actions/checkout@v4
      - run: packer build -force .
        working-directory: packer
      - run: cp /var/lib/lab/images/${{ github.event.release.tag_name  }}/debian-k8s-base.qcow2 ansible/images/current/debian-k8s-base.qcow2

  tofu-validate:                   
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: tofu init
        working-directory: terraform
      - run: tofu fmt -check
        working-directory: terraform
      - run: tofu validate
        working-directory: terraform

  tofu-plan:                   
    runs-on: self-hosted
    needs: [tofu-validate]
    if: ${{ always() && inputs.tofu && needs.packer-deploy.result != 'failure' && needs.packer-deploy.result != 'cancelled' && github.event_name  == 'release' }}
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4    
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}         
          aws-region: eu-central-1
          audience: sts.amazonaws.com
      - run: tofu init
        working-directory: terraform
      - run: tofu plan -out=tfplan -lock=false
        working-directory: terraform
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
          retention-days: 1

  tofu-deploy:
    needs: [tofu-plan, packer-deploy]
    runs-on: self-hosted
    environment: prod
    if: github.event_name  == 'release'
    env:
      TF_VAR_IMAGE_TAG: ${{ github.event.release.tag_name  }}  
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4    
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}          
          aws-region: eu-central-1
          audience: sts.amazonaws.com
      - run: tofu init
        working-directory: terraform
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform
      - run: tofu apply tfplan -auto-approve
        working-directory: terraform

  ansible-validate:                
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/ansible-lint:latest
    steps:
      - uses: actions/checkout@v4
      - run: ansible-lint -f pep8
        working-directory: packer
      - run: ansible-lint -f pep8
        working-directory: ansible
      - run: ansible-playbook --syntax-check k8s-pre.yaml
        working-directory: packer
      - run: ansible-playbook --syntax-check k8s-post.yaml
        working-directory: ansible
  ansible-deploy:
    needs: [ansible-validate, tofu-deploy]
    runs-on: self-hosted
    environment: prod
    if: ${{ always() && inputs.ansible && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - run: ansible-playbook -i ../inventory.yaml k8s-post.yaml
        working-directory: ansible