name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  packer-validate:                     
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: packer validate -syntax-only .
        working-directory: packer
  packer-deploy:
    needs: packer-validate
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: packer build .
        working-directory: packer

  tofu-plan:                   
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: tofu init
        working-directory: terraform
      - run: tofu fmt -check
        working-directory: terraform
      - run: tofu validate
        working-directory: terraform
      - run: tofu plan
        working-directory: terraform
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
          retention-days: 1

  tofu-deploy:
    needs: tofu-plan
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: tofu init
        working-directory: terraform
      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform
      - run: tofu apply tfplan -auto-approve
        working-directory: terraform

  ansible-validate:                
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ansible-lint
        working-directory: ansible
      - run: ansible-playbook --syntax-check k8s-pre.yaml
        working-directory: ansible
      - run: ansible-playbook --syntax-check k8s-post.yaml
        working-directory: ansible
  ansible-deploy:
    needs: ansible-validate
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: ansible-playbook -i inventory.yml k8s-post.yaml
        working-directory: ansible